// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzlvrflmawihndfsavpg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56bHZyZmxtYXdpaG5kZnNhdnBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1ODYyMDEsImV4cCI6MjA2NTE2MjIwMX0.NmW93E0g8ihvK-huXIhYj5JO7FnvjU_1kD18QdsX2Fo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);